BE/README.md
FE/README.md
docs/README.md

[SETTING] 분야별 디렉토리 생성

---

FE/.gitignore
FE/package-lock.json
FE/package.json
FE/public/manifest.json
FE/public/robots.txt
FE/src/App.css
FE/src/App.js
FE/src/index.css
FE/src/index.js

[FEAT/FE] 폴더 구조 생성

---

BE/chackcheck/.gitignore

> ex) #21 
mac에서 git ignore해야할 파일 추가 설정하였습니다.

chore: git ignore mac 추가 설정

---

FE/src/App.css
FE/src/App.js
FE/src/components/common/Category.jsx
FE/src/components/common/header/header.jsx
FE/src/components/common/header/logo.jsx
FE/src/components/common/infoList/infoTable.jsx
FE/src/components/common/pagination.jsx
FE/src/pages/book.jsx

[FE/FEAT] Books 페이지 화면 구성

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebConfig.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/Book.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookCategory.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookRegister.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/Category.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookCategoryRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookDetailRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookRegisterRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/CategoryRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/controller/BookBorrowController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/domain/BookBorrow.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/domain/BookReserve.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/BookBorrowService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/Role.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/Penalty.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/Role.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java

---
labels: ''
assignees: ''
---
> #40 
> 폴더 구조를 변경하였습니다.

[BE/REFACTOR] 폴더 구조 변경

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java

[BE/REFACTOR] BookDetail 도메인 수정

---

BE/chackcheck/build.gradle
BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/TokenController.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/domain/RefreshToken.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/dto/CreateAccessTokenRequest.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/dto/CreateAccessTokenResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/repository/RefreshTokenRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/service/RefreshTokenService.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/service/TokenService.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/TokenAuthenticationFilter.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/jwt/JwtProperties.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/jwt/TokenProvider.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/repository/UserRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserDetailService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java
BE/chackcheck/src/main/resources/application.yml
BE/chackcheck/src/test/java/sigma/chackcheck/config/jwt/JwtFactory.java
BE/chackcheck/src/test/java/sigma/chackcheck/config/jwt/TokenProviderTest.java

> #50 
> User 도메인 변경
> 토큰 생성 구현
> 리프레쉬 토큰 구현

[BE/FEAT] 시큐리티 설정, JWT 토큰 생성

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookCategory.java

[BE/REFACTOR] 변수명 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/config/SecurityWebConfig.java

> 
> SecurityWebConfig를 추가했습니다.

[BE/FEAT] SecurityWebConfig 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/pagination/service/Pagination.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookCategory.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookCategoryRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java

> #59 
> 도서카테고리 이름으로 도서 페이지 반환하는 api를 만들었습니다.

[BE/feat] getBookPageByCategoryName api

---

FE/user_pages/package-lock.json
FE/user_pages/package.json
FE/user_pages/src/components/common/home/SearchBar.jsx
FE/user_pages/src/components/common/pagination.jsx
FE/user_pages/src/pages/main.jsx

---
labels: ''
assignees: ''
---
#55 
서치바의 api 요청 부분을 삭제하고 검색 시 주소 수정 부분 리팩토링

[FE/fix] 서치바 api 요청 삭제 및 css 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/pagination/service/Pagination.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java

[BE/FEAT] 도서 검색 기능 구현

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/pagination/service/Pagination.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookApprove.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApprovePageResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookApproveRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java

> #64 
> 도서 승인 목록 조회 기능을 구현했습니다.

[BE/FEAT] 도서 승인 목록 조회 기능 구현

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/service/GetEntityUsecase.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/service/Pagination.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookDetailDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookDetailPageResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/FullBookDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookDetailRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBookUsecase.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/dto/response/BookBorrowAvailableDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/dto/response/BookBorrowDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/repository/BookBorrowRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/BookBorrowService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/GetBookBorrow.java

> #66 
> 도서 상세 정보 조회 api를 구현했습니다.

[BE/FEAT] 도서 상세 정보 조회 api 구현

---

FE/user_pages/src/pages/main.jsx

[FE/FIX] api 명 수정 

---

FE/user_pages/src/pages/book.jsx
FE/user_pages/src/pages/main.jsx

[FE/FIX] api 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/CustomLogoutHandler.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/CustomLogoutSuccessHandler.java
BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/LoginSuccessJWTProvideHandler.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/TokenAuthenticationFilter.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java

> # 92
> 시큐리티를 이용한 로그아웃 기능 구현
> 리팩토링 필요함

[BE/FEAT] 로그아웃 기능 구현

---

BE/chackcheck/src/main/java/sigma/chackcheck/auth/controller/LoginSuccessJWTProvideHandler.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java
BE/chackcheck/src/main/java/sigma/chackcheck/common/config/jwt/TokenProvider.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/Role.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
BE/chackcheck/src/test/java/sigma/chackcheck/user/userTest.java

[BE/FEAT] admin 인가 설정

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookController.java

[BE/REFACTOR] admin api 분리

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java

> none
> admin controller 메서드 이름 변경

[BE/FIX] 에러 해결

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/repository/BookBorrowRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/BookRentInfoResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/BookRentInfosResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserBorrowHistoryService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java

[BE/FEAT] 대출 이력 조회

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/domain/BookBorrow.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/dto/response/BookBorrowDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/PutBookBorrow.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/request/AddUserRequest.java

[BE/FEAT] dueDate 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/BookController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookDetail.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookDetailRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java

[BE/FEAT] 도서 정보 삭제 기능

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/repository/BookBorrowRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/BookRentInfoResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserBorrowHistoryService.java

[BE/FEAT] 현재 대출 중인 도서 조회

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/request/AddUserRequest.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java

> #119 
> 회원 등록 request 수정
> name 추가

[BE/FIX] 회원 등록 

---

BE/chackcheck/src/main/java/sigma/chackcheck/ChackcheckApplication.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/GetBook.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/bookBorrow/service/BookBorrowService.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/Penalty.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/domain/User.java

> ex) none
> 
1. 연체한 사용자는 도서를 빌리지 못하게 하는 기능 추가
2. 도서가 존재할 때 도서정보만 추가하는 로직 추가

[BE/FEAT] 추가 기능 구현

---

FE/admin_pages/src/components/common/Category.jsx
FE/admin_pages/src/components/common/Form.jsx
FE/admin_pages/src/pages/RegisterMember.jsx

---
labels: ''
assignees: ''
---
> ex) #122 
> 글 등록 페이지 API 수정
카테고리 링크 문제 해결

[FE/FIX] 글 등록 페이지 API 수정 및 카테고리 링크 문제 해결

---

FE/admin_pages/src/pages/BookApporovePage.jsx
FE/admin_pages/src/pages/BookList.jsx
FE/admin_pages/src/pages/login.jsx
FE/user_pages/src/pages/login.jsx

[FE/Fix]관리자 로그인 페이지 링크

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookInfoDTO.java

feat: 임시 코드

---

BE/chackcheck/src/main/java/sigma/chackcheck/common/config/WebSecurityConfig.java

[BE/FIX] 3002 포트 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/repository/BookCategoryRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java

feat: 관리자 도서 관리 페이지

---

BE/chackcheck/src/main/java/sigma/chackcheck/S3/S3Service.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java

[BE/FEAT] dto에 이미지 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/S3/S3Service.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookDTO.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/FullBookDTO.java

[BE/FEAT] 원상태로 복구하면서 BookDto에 imageUrl 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/CurruentBorrowedBook.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/CurruentBorrowedBooks.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserInfo.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserInfos.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/dto/response/UserPageAdminResponse.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/repository/UserRepository.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java

[BE/FEAT] 유저 전체 조회 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java

---
labels: ''
assignees: ''
---

refactor: uri 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/controller/admin/BookAdminController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java

[BE/FEAT] 도서 승인 삭제 추가

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/domain/BookApprove.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java

[BE/FEAT] 기본 이미지 추가

---

FE/user_pages/src/components/common/pagination.jsx

---
labels: ''
assignees: ''
---

[FE/FIX] 페이지네이션 api 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/BookApproveDTO.java

feat: BookApproveDTO 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/service/BookService.java

feat: 소문자/대문자 해결

---

FE/admin_pages/src/App.js
FE/admin_pages/src/components/common/Category.jsx
FE/admin_pages/src/components/common/Detail.jsx
FE/admin_pages/src/components/common/pagination.jsx
FE/admin_pages/src/pages/BookApporovePage.jsx
FE/admin_pages/src/pages/BookList.jsx
FE/admin_pages/src/pages/RegisterMember.jsx
FE/admin_pages/src/pages/UserList.jsx
FE/admin_pages/src/pages/login.jsx
FE/user_pages/src/components/common/pagination.jsx
FE/user_pages/src/pages/MyPage.jsx
FE/user_pages/src/pages/login.jsx

---
labels: ''
assignees: ''
---

[FE/FIX] 페이지네이션 및 관리자페이지 api 수정

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/controller/UserController.java
BE/chackcheck/src/main/java/sigma/chackcheck/domain/user/service/UserService.java

feat: 회원 가입 수정

---

FE/admin_pages/src/pages/RegisterMember.jsx

---
labels: ''
assignees: ''
---

[FE/FIX] 유저 등록 api

---

BE/chackcheck/src/main/java/sigma/chackcheck/domain/book/dto/response/FullBookDTO.java

refactor: 도서 상세 정보 조회 dto 변경

---

FE/admin_pages/src/components/common/Form.jsx
FE/admin_pages/src/components/common/buttons/SelectApporove.jsx
FE/admin_pages/src/pages/BookList.jsx
FE/user_pages/src/components/common/Detail.jsx
FE/user_pages/src/components/common/Form.jsx
FE/user_pages/src/components/common/home/BookList.jsx

---
labels: ''
assignees: ''
---

[FE/FIX] 도서등록 예외처리
